RETURN_SOURCE_DOCUMENTS: True
VECTOR_COUNT: 10
CHUNK_SIZE: 3000
CHUNK_OVERLAP: 300
DATA_PATH: 'data/'
DB_FAISS_PATH: 'vectorstore/db_faiss'
MODEL_TYPE: 'mistral'
MODEL_BIN_PATH: 'models/mistral-7b-instruct-v0.1.Q8_0.gguf'
EMBEDDINGS: 'sentence-transformers/all-mpnet-base-v2'
MAX_NEW_TOKENS: 12000
TEMPERATURE: 0.01